// This file is autogenerated. Changes will be overwritten.
#include "OTUN7GXZT4/moc_calculator.cpp"
#include "OTUN7GXZT4/moc_credit.cpp"
#include "OTUN7GXZT4/moc_mainwindow.cpp"
#include "OTUN7GXZT4/moc_qcustomplot.cpp"
